title: Site

columns:
  - width: 1/3
    sections:
    type: fields
    fields:
      programmHeaderTitle:
        label: Programm Button
        type: text
        help: Sprache anpassen
        required: true
  - width: 1/3
    sections:
    type: fields
    fields:
      aboutHeaderTitle:
        label: About Button
        type: text
        help: Sprache anpassen
        required: true
  - width: 1/3
    sections:
    type: fields
    fields:
      contactHeaderTitle:
        label: Kontakt Button
        type: text
        help: Sprache anpassen
        required: true
  - width: 1/3
    sections:
      pages:
        label: Crowdfounding 
        type: pages
        layout: cardlets
        status: listed
        image:
          color: none
          back: black