title: Site

columns:
  - width: 1/1
    sections:
      pages:
        label: Seiten
        type: pages
        layout: cards
        status: listed
        image:
          query: page
          back: black
          color: white

  - width: 1/3
    sections:
    type: fields
    fields:
      hometitle:
        label: Titel (nicht ändern!)
        type: text
        required: true